version: '3.8'

services:
  # MongoDB Service
  mongo:
    image: mongo:7.0
    container_name: task-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: taskdb
    networks:
      - task-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Node.js API Service
  api:
    image: ${DOCKER_USERNAME:-sri2710}/task-api:latest
    container_name: task-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://mongo:27017/taskdb
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - task-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 3s
      start_period: 40s
      retries: 3

volumes:
  mongo-data:

networks:
  task-network:
    driver: bridge